import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/src/components/header";
import ActiveSectionContextProvider from "../context/active-section-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Personal dashboard",
  description: "Generated by Zard",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`${inter.className} bg-gray-50 text-gray-950 relative pt-28 
        sm:pt-36 dark:bg-gray-900 dark:text-gray-50 dark:text opacity-80`}
      >
        <div
          className="bg-[#fbe2e3] absolute top-[-6rem] -z-10
         right-[11rem] h-[31.25rem] w-[31.25rem] rounded-full
         blur-[10rem] sm:w-[68.75rem] dark:bg-[#946263]"
        ></div>
        <ActiveSectionContextProvider>
          <Header />
          {children}
        </ActiveSectionContextProvider>
      </body>
    </html>
  );
}
